version: '2'

services:

  elasticsearch:
    build:
      context: elk/docker-elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms512m -XX:+UseGCOverheadLimit"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk


  kibana:
    build:
      context: elk/docker-elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elk/docker-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  dashboard:
    build:
      context: dashboard/
    volumes:
      - ../app/guinicorn_access.log:/app/guinicorn_access.log
      - ../app/guinicorn_error.log:/app/guinicorn_error.log
    
    ports:
      - "5000:5000"
    environment:
      - LC_ALL=en_US.utf-8
      - LANG=en_US.utf-8
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge